name: CI/CD for Laravel in Monorepo

on:
  push:
    branches:
      - main  # Atur branch sesuai dengan branch yang Anda gunakan
  pull_request:
    branches:
      - main

jobs:
  laravel-ci-cd:
    runs-on: ubuntu-latest


    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Production Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

